language: java
sudo: false
env:
 - GRADLE_USER_HOME=gradle-cache
 
cache:
  directories:
   - gradle-cache
   - netbeans

branches:
  only:
  - master

notifications:
  slack:
    secure: "Tuoa63n2iJT/JrdmGggnzJRHo7yPigvoEIObddYU2uw4iAkoGhXO125V4z92bggD5idVX/CNr8SCHTgbomzvtq9VrozW75ta2NDMt0bgR9tuxK12QzZpGtU6togU7S0j/0rUrOFi8B3paIc9SfCX6T+hB+Z2hGz8UMpnFuh6xJc="

before_install:
  # required libs for android build tools
  # sudo apt-get update
  # sudo apt-get install -qq p7zip-full
  # sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  # newest Android NDK
  # wget http://dl.google.com/android/ndk/android-ndk-r10c-linux-x86_64.bin -O ndk.bin
  # 7z x ndk.bin -y > /dev/null
  # export ANDROID_NDK=`pwd`/android-ndk-r10c
